package models

const (
	BLOCK                         = "blocks"
	BLOCK_THREAD                  = "block_threads"
	BLOCK_THREAD_COMMENT          = "block_comments"
	CANVAS_BRANCH                 = "canvas_branches"
	CANVAS_BRANCH_PUBLIC_REQUEST  = "canvas_branch_public_requests"
	CANVAS_REPO                   = "canvas_repositories"
	COLLECTION                    = "collections"
	FOLLOW_STUDIO                 = "follow_studios"
	FOLLOW_USER                   = "follow_users"
	GROUP                         = "groups"
	MEMBER                        = "members"
	CANVAS_BRANCH_PERMISSION      = "canvas_branch_permissions"
	COLLECTION_PERMISSION         = "collection_permissions"
	STUDIO_PERMISSION             = "studio_permissions"
	ROLE                          = "roles"
	STUDIO                        = "studios"
	TOPIC                         = "topics"
	USER                          = "users"
	USER_CONTACT                  = "user_contacts"
	USER_SETTINGS                 = "user_settings"
	USER_PROFILE                  = "user_profiles"
	USER_ASSOCIATED_STUDIO        = "user_associated_studios"
	USER_SOCIAL_AUTH              = "user_social_auths"
	STUDIO_INTEGRATION            = "studio_integrations"
	REEL                          = "reels"
	REEL_COMMENTS                 = "reel_comments"
	BLOCKREACTION                 = "block_reactions"
	BLOCKTHREADREACTION           = "block_thread_reactions"
	BLOCKCOMMENTREACTION          = "block_comment_reactions"
	REELREACTION                  = "reel_reactions"
	REELCOMMENTREACTION           = "reel_comment_reactions"
	MERGEREQUEST                  = "merge_requests"
	CANVAS_BRANCH_PUBLISH_REQUEST = "canvas_branch_publish_requests"
	PUBLISHREQUEST                = "publish_requests"
	BRANCH_ACCESS_TOKEN           = "branch_access_tokens"
	ACCESSREQUEST                 = "access_requests"
	NOTIFICATIONS                 = "notifications"
	POST                          = "posts"
)
