package parser2

//
//var PlainTextMapper = map[string]func(blockType string, block models.Block) string{
//	models.BlockTypeText:                PT_BlockTypeText,
//	models.BlockTypeHeading1:            PT_BlockTypeHeading1,
//	models.BlockTypeHeading2:            PT_BlockTypeHeading2,
//	models.BlockTypeHeading3:            PT_BlockTypeHeading3,
//	models.BlockTypeHeading4:            PT_BlockTypeHeading4,
//	models.BlockTypeHeading5:            PT_BlockTypeHeading5,
//	models.BlockTypeHeading6:            PT_BlockTypeHeading6,
//	models.BlockTypeCode:                PT_BlockTypeCode,
//	models.BlockTypeCallout:             PT_BlockTypeCallout,
//	models.BlockTypeTweet:               PT_BlockTypeTweet,
//	models.BlockTypeImage:               PT_BlockTypeImage,
//	models.BlockTypeUList:               PT_BlockTypeUList,
//	models.BlockTypeOList:               PT_BlockTypeOList,
//	models.BlockTypeListItem:            PT_BlockTypeListItem,
//	models.BlockTypeAttachment:          PT_BlockTypeAttachment,
//	models.BlockTypeVideo:               PT_BlockTypeVideo,
//	models.BlockTypeCheckList:           PT_BlockTypeCheckList,
//	models.BlockTypeGoogleMap:           PT_BlockTypeGoogleMap,
//	models.BlockTypeFigma:               PT_BlockTypeFigma,
//	models.BlockTypeCodePen:             PT_BlockTypeCodePen,
//	models.BlockTypeReplit:              PT_BlockTypeReplit,
//	models.BlockTypeCodeSandBox:         PT_BlockTypeCodeSandBox,
//	models.BlockTypeGoogleDrive:         PT_BlockTypeGoogleDrive,
//	models.BlockTypeGoogleSheet:         PT_BlockTypeGoogleSheet,
//	models.BlockTypeMiro:                PT_BlockTypeMiro,
//	models.BlockTypeExcaliDraw:          PT_BlockTypeExcaliDraw,
//	models.BlockTypeOgMetaTag:           PT_BlockTypeOgMetaTag,
//	models.BlockTypeYoutube:             PT_BlockTypeYoutube,
//	models.BlockTypeLoom:                PT_BlockTypeLoom,
//	models.BlockTypeDivider:             PT_BlockTypeDivider,
//	models.BlockTypeImportNotionMention: PT_BlockTypeImportNotionMention,
//	models.BlockTypeTempTable:           PT_BlockTypeTempTable,
//	models.BlockTypeSimpleTable:         PT_BlockTypeSimpleTable,
//	models.BlockMentions:                PT_BlockMentions,
//}
