package configs

const (
	API_HOST         = "API_HOST"
	SITE_ROOT        = "SITE_ROOT"
	SECRET_SHORT_KEY = "SECRET_SHORT_KEY"

	ENV_KEY        = "ENV"
	ENV_PRODUCTION = "production"
	ENV_LOCAL      = "local"
	ENV_DEV        = "dev"

	PG_HOST_KEY = "PG_HOST"
	PG_PORT_KEY = "PG_PORT"
	PG_USER_KEY = "PG_USER"
	PG_PASS_KEY = "PG_PASS"
	PG_NAME_KEY = "PG_NAME"

	REDIS_HOST_KEY = "REDIS_HOST"
	REDIS_PORT_KEY = "REDIS_PORT"
	REDIS_PASS_KEY = "REDIS_PASS"

	S3_ACCESS_KEY_ID     = "S3_ACCESS_KEY_ID"
	S3_SECRET_ACCESS_KEY = "S3_SECRET_ACCESS_KEY"
	S3_BUCKET_NAME       = "S3_BUCKET_NAME"
	S3_REGION            = "S3_REGION"
	S3_CLOUDFRONT_URL    = "S3_CLOUDFRONT_URL"

	DISCORD_APP_ID                 = "DISCORD_APP_ID"
	DISCORD_PUBLIC_KEY             = "DISCORD_PUBLIC_KEY"
	DISCORD_CLIENT_ID              = "DISCORD_CLIENT_ID"
	DISCORD_CLIENT_SECRET          = "DISCORD_CLIENT_SECRET"
	DISCORD_TOKEN                  = "DISCORD_TOKEN"
	DISCORD_PERMISSION             = "DISCORD_PERMISSION"
	DISCORD_LAMBDA_SERVER_ENDPOINT = "DISCORD_LAMBDA_SERVER_ENDPOINT"

	KAFKA_HOSTS_KEY        = "KAFKA_HOSTS"
	KAFKA_CONSUMER_ENABLED = "KAFKA_CONSUMER_ENABLED"

	ALGOLIA_APP_ID        = "ALGOLIA_APP_ID"
	ALGOLIA_ADMIN_API_KEY = "ALGOLIA_ADMIN_API_KEY"

	SLACK_APP_ID                 = "SLACK_APP_ID"
	SLACK_CLIENT_ID              = "SLACK_CLIENT_ID"
	SLACK_CLIENT_SECRET          = "SLACK_CLIENT_SECRET"
	SLACK_SIGNING_SECRET         = "SLACK_SIGNING_SECRET"
	SLACK_NONCE                  = "SLACK_NONCE"
	SLACK_LAMBDA_SERVER_ENDPOINT = "SLACK_LAMBDA_SERVER_ENDPOINT"
	GIT_HOSTS                    = "GIT_HOSTS"
	GIT_SECRET_KEY               = "GIT_SECRET_KEY"

	GET_STREAM_API_KEY    = "GET_STREAM_API_KEY"
	GET_STREAM_API_SECRET = "GET_STREAM_API_SECRET"

	FRONTEND_HOST = "FRONTEND_HOST"
	BACKEND_HOST  = "BACKEND_HOST"

	SUPABASE_BASEURL = "SUPABASE_BASEURL"
	SUPABASE_TOKEN   = "SUPABASE_TOKEN"

	SENTRY_DSN       = "SENTRY_DSN"
	STAGE_EMAIL      = "bip.so stage <stage@stage-emails.dev.bip.so>"
	PRODUCTION_EMAIL = "bip.so <team@notifications.bip.so>"

	STRIPE_SECRET_KEY = "STRIPE_SECRET_KEY"
)

const (
	PAGINATION_LIMIT = 20
)
