package configs

const (
	KAFKA_TOPICS_NEW_USER    = "newUsers"
	KAFKA_TOPICS_UPDATE_USER = "updateUser"

	KAFKA_TOPICS_COMMENTS = "comments"

	KAFKA_TOPICS_NOTIFICATIONS = "notifications"

	KAFKA_TOPICS_NEW_STUDIO     = "newStudio"
	KAFKA_TOPICS_UPDATE_STUDIO  = "updateStudio"
	KAFKA_TOPICS_DELETED_STUDIO = "deletedStudio"

	KAFKA_TOPICS_NEW_CANVAS            = "newCanvas"
	KAFKA_TOPICS_DELETED_CANVAS        = "deletedCanvas"
	KAKFA_TOPICS_CALCULATE_PERMISSIONS = "calculatePermissions"
	KAFKA_TOPIC_STUDIO_INTEGRATED      = "studioIntegrated"

	KAFKA_TOPICS_EMAILS      = "emails"
	KAFKA_INTEGRATION_EVENTS = "integrationEvents"
)

var KAFKA_CONSUMER_GROUP_TOPICS = []string{
	KAFKA_TOPICS_COMMENTS,
	KAFKA_TOPICS_NOTIFICATIONS,
	KAFKA_TOPICS_NEW_USER,
	KAFKA_TOPICS_UPDATE_USER,
	KAFKA_TOPICS_NEW_STUDIO,
	KAFKA_TOPICS_UPDATE_STUDIO,
	KAFKA_TOPICS_DELETED_STUDIO,
	KAFKA_TOPICS_NEW_CANVAS,
	KAKFA_TOPICS_CALCULATE_PERMISSIONS,
	KAFKA_TOPICS_DELETED_CANVAS,
	KAFKA_TOPICS_EMAILS,
	KAFKA_INTEGRATION_EVENTS,
}
var KAFKA_CONSUMER_GROUP_ID = "bip-be-platform"
